version: '2'

services:
  es:
    build: ./es
    container_name: es
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    build: ./kibana
    container_name: kibana
    ports:
     - 5601:5601
    depends_on:
      - es
    environment:
      ELASTICSEARCH_URL: http://es:9200

volumes:
  es_data:
    driver: local