# To get the latest version of images list you can look
#  https://www.docker.elastic.co/
# 
# Copyright (c) Vybhava Technologies and affiliates. All rights reserved.
#
FROM docker.elastic.co/kibana/kibana:7.5.1
# More document details: https://www.elastic.co/guide/en/kibana/7.5/docker.html
#
# Maintainer
# ----------
LABEL MAINTAINER BhavaniShekhar
